<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-28T10:44:27 IST" name="Suite2" finished-at="2022-09-28T10:44:50 IST" duration-ms="22734">
    <groups>
    </groups>
    <test started-at="2022-09-28T10:44:27 IST" name="Chrome test" finished-at="2022-09-28T10:44:50 IST" duration-ms="22734">
      <class name="pack1.TestNg_Login_Retesting">
        <test-method is-config="true" signature="LaunchBrowser(java.lang.String)[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:27 IST" name="LaunchBrowser" finished-at="2022-09-28T10:44:29 IST" duration-ms="1723" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method is-config="true" signature="createPomObjects()[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:29 IST" name="createPomObjects" finished-at="2022-09-28T10:44:29 IST" duration-ms="66" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPomObjects -->
        <test-method is-config="true" signature="Verify_Login_and_CreateNewAccount()[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:29 IST" name="Verify_Login_and_CreateNewAccount" finished-at="2022-09-28T10:44:31 IST" duration-ms="2005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login_and_CreateNewAccount -->
        <test-method signature="Verify_Login_Credentials()[pri:1, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:31 IST" name="Verify_Login_Credentials" finished-at="2022-09-28T10:44:37 IST" duration-ms="5964" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null
at Utils.Utility.getDataFromExcelSheet(Utility.java:41)
at pack1.TestNg_Login_Retesting.Verify_Login_Credentials(TestNg_Login_Retesting.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login_Credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:37 IST" name="afterMethod" finished-at="2022-09-28T10:44:37 IST" duration-ms="225" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verify_Login_Credentials status=FAILURE method=TestNg_Login_Retesting.Verify_Login_Credentials()[pri:1, instance:pack1.TestNg_Login_Retesting@2e005c4b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="Verify_Login_and_CreateNewAccount()[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:37 IST" name="Verify_Login_and_CreateNewAccount" finished-at="2022-09-28T10:44:38 IST" duration-ms="736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login_and_CreateNewAccount -->
        <test-method signature="Verify_Login_Credentials()[pri:1, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:38 IST" name="Verify_Login_Credentials" finished-at="2022-09-28T10:44:43 IST" duration-ms="5168" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null
at Utils.Utility.getDataFromExcelSheet(Utility.java:41)
at pack1.TestNg_Login_Retesting.Verify_Login_Credentials(TestNg_Login_Retesting.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login_Credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:43 IST" name="afterMethod" finished-at="2022-09-28T10:44:43 IST" duration-ms="211" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verify_Login_Credentials status=FAILURE method=TestNg_Login_Retesting.Verify_Login_Credentials()[pri:1, instance:pack1.TestNg_Login_Retesting@2e005c4b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="Verify_Login_and_CreateNewAccount()[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:43 IST" name="Verify_Login_and_CreateNewAccount" finished-at="2022-09-28T10:44:44 IST" duration-ms="710" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login_and_CreateNewAccount -->
        <test-method signature="Verify_Login_Credentials()[pri:1, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:44 IST" name="Verify_Login_Credentials" finished-at="2022-09-28T10:44:50 IST" duration-ms="5387" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null
at Utils.Utility.getDataFromExcelSheet(Utility.java:41)
at pack1.TestNg_Login_Retesting.Verify_Login_Credentials(TestNg_Login_Retesting.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login_Credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:50 IST" name="afterMethod" finished-at="2022-09-28T10:44:50 IST" duration-ms="202" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Verify_Login_Credentials status=FAILURE method=TestNg_Login_Retesting.Verify_Login_Credentials()[pri:1, instance:pack1.TestNg_Login_Retesting@2e005c4b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="removeObjects()[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:50 IST" name="removeObjects" finished-at="2022-09-28T10:44:50 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removeObjects -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:pack1.TestNg_Login_Retesting@2e005c4b]" started-at="2022-09-28T10:44:50 IST" name="afterClass" finished-at="2022-09-28T10:44:50 IST" duration-ms="274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- pack1.TestNg_Login_Retesting -->
    </test> <!-- Chrome test -->
  </suite> <!-- Suite2 -->
</testng-results>
